### PR TITLE
Fixes an issue with using inline-tinymce

### PR DESCRIPTION
**Pull request by Manuel-S**
when using tinymce with the option inline: true, it can be used on any html element. In that case, the binding must set the html instead of text-value of that element.

I tried to update the coffee source this time, js needs to be generated.

### CODE REVIEW

**Comment by Manuel-S** [comment]
have you looked at this yet?

**Comment by Manuel-S** [comment]
I fixed the coffeescript and regenerated the javascript.

**Comment by cmbankester** [comment]
@Manuel-S Cool, thanks! Sorry I never got back to you originally. Do you have a small demo case where this fix might be used, i.e. some code or perhaps a gif?

**Comment by Manuel-S** [comment]
easy:

``` html
<div data-bind="tinymce: vmProperty, tinymceConfig: { inline: true }"></div> 
```

if you do this without the fix, all the html in vmProperty will be escaped on init.

**Comment by cmbankester** [comment]
@Manuel-S Looks good. I'll merge it in and recompile (to produce the `knockout-tinymce.min.js` file). Thanks for your work!

**Comment by Manuel-S** [comment]
I did that but go ahead :)

**Comment by cmbankester** [comment]
Oh good, I didn't even see that! Awesome, you rock

**Pull request merged**
